analytics:
  twitter: null
  facebook: null
  google: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.3897
title: My new attempt at photography
cta:
  version: null
  bucket: null
  domain: null
purpose: []
color:
  saturation: 1
  brandStrength: 0.6875
  rhythmicContrast: 0.8239349
  brandColors:
    - '#010101'
    - '#443751'
    - '#a34b49'
    - '#d7746f'
    - '#ffb885'
  lightness: 0.8189223
favicon: null
typography_spectrum: 0.58238
name: 'andrés e. munárriz soto - a new attempt at photography '
