name: 'andrés e. munárriz soto - a new attempt at photography '
favicon: null
layout_spectrum: 0.3897
typography_spectrum: 0.58238
title: My new attempt at photography
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#443751'
    - '#a34b49'
    - '#d7746f'
    - '#ffb885'
  brandStrength: 0.6875
  lightness: 0.8189223
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
