name: Andrés Munárriz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38777
title: My new attempt at photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aab575'
    - '#777449'
    - '#563b24'
    - '#090e0a'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
