color:
  brandStrength: 0.6875
  saturation: 0.375
  brandColors:
    - '#010101'
    - '#443751'
    - '#a34b49'
    - '#d7746f'
    - '#ffb885'
  lightness: 0.8189223
  rhythmicContrast: 0.25
title: My new attempt at photography
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.3897
purpose: []
name: 'andrés e. munárriz soto - a new attempt at photography '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.58238
