title: My new attempt at photography
cta:
  domain: null
  version: null
  bucket: null
layout_spectrum: 0.3897
favicon: null
name: 'andrés e. munárriz soto - a new attempt at photography '
purpose: []
analytics:
  facebook: null
  google: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
color:
  brandStrength: 0.6875
  lightness: 0.8189223
  saturation: 1
  rhythmicContrast: 0.8239349
  brandColors:
    - '#010101'
    - '#443751'
    - '#a34b49'
    - '#d7746f'
    - '#ffb885'
typography_spectrum: 0.58238
