title: My new attempt at photography
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.3834586
favicon: null
name: Andrés Munárriz
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.4417293
  saturation: 0.8057644
  rhythmicContrast: 0.3333333
  brandColors:
    - '#130002'
    - '#2C281C'
    - '#72434D'
    - '#BD8183'
    - '#DEAD75'
typography_spectrum: 0.38777
