title: My new attempt at photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 0.3125
  lightness: 0.4375
  brandColors:
    - '#ffffff'
    - '#aab575'
    - '#777449'
    - '#563b24'
    - '#090e0a'
  rhythmicContrast: 0.2401434
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Andrés Munárriz
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.38777
layout_spectrum: 1
