name: 'andrés e. munárriz soto - a new attempt at photography '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38777
title: My new attempt at photography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#443751'
    - '#a34b49'
    - '#d7746f'
    - '#ffb885'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.125
  rhythmicContrast: 0.2401434
purpose: []
